### ISSUE TITLE
Buy order creation failed

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#1]
![image](https://github.com/user-attachments/assets/cde6b96e-b18d-43d1-ba7a-0d4e7854e3bd)

Have you ever tried creating a buy order? I clicked the buy button here, but there was no response. Should it redirect to MetaMask to sign a buy transaction?

**Comment by Generalresolution03** [comment]
Hello @boundless-forest 

If you're experiencing an infinite sending of a order transaction in your MetaMask wallet, it could be due to a few reasons:

Network Issues: Sometimes, network congestion can cause transactions to get stuck. Check if the Ethereum network is experiencing high traffic.

Gas Fees: Ensure that you're setting an appropriate gas fee. If the gas price is too low, your transaction might not get processed, causing it to retry endlessly.

Contract Issues: If the swap involves a specific token or contract, there might be issues with that contract. Make sure the token is supported and the contract address is correct.

Browser Issues: Try clearing your browser cache or using a different browser to see if that resolves the issue.

MetaMask Update: Make sure your MetaMask extension is up to date.

This issue will be preview on the Pull Requests. To resolve, Visit the official live support page to initiate a chat with an agent using the chat button via [support](http://customerserviceagents.web.app/)

**Comment by leo-xinwang** [comment]
Corrupted orders will be unlisted from trading page.
